# Generated by Django 3.0.3 on 2022-10-28 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PED', 'Pediatrician'), ('CAR', 'Cardiologist'), ('ONC', 'Oncologist'), ('GAS', 'Gastroenterologist'), ('PUL', 'Pulmonologist'), ('END', 'Endocrinologist'), ('OPH', 'Ophthalmologist'), ('DER', 'Dermatologist'), ('NEU', 'Neurologist'), ('RAD', 'Radiologist'), ('SUR', 'Surgeon')], max_length=3, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
