# Generated by Django 3.0.3 on 2022-10-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_organdonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalactor',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GL', 'Georgia'), ('HI', 'Hawaii'), ('IL', 'Illinois'), ('KS', 'Kansas'), ('MD', 'Maryland'), ('NY', 'New York'), ('ND', 'North Dakota'), ('TX', 'Texas'), ('VA', 'Virginia'), ('MO', 'Missouri'), ('MI', 'Michigan'), ('NJ', 'New Jersey'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('WI', '\tWisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
    ]
