# Generated by Django 3.0.3 on 2022-10-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221029_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organdonation',
            name='patient',
        ),
        migrations.AddField(
            model_name='organdonation',
            name='address1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='address2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='apt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='category',
            field=models.CharField(choices=[('PED', 'Pediatrician'), ('CAR', 'Cardiologist'), ('ONC', 'Oncologist'), ('GAS', 'Gastroenterologist'), ('PUL', 'Pulmonologist'), ('END', 'Endocrinologist'), ('OPH', 'Ophthalmologist'), ('DER', 'Dermatologist'), ('NEU', 'Neurologist'), ('RAD', 'Radiologist'), ('SUR', 'Surgeon')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='is_organ_donated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GL', 'Georgia'), ('HI', 'Hawaii'), ('IL', 'Illinois'), ('KS', 'Kansas'), ('MD', 'Maryland'), ('NY', 'New York'), ('ND', 'North Dakota'), ('TX', 'Texas'), ('VA', 'Virginia'), ('MO', 'Missouri'), ('MI', 'Michigan'), ('NJ', 'New Jersey'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('WI', '\tWisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
