# Generated by Django 3.0.3 on 2022-10-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221030_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='organdonation',
            name='organ_type',
            field=models.CharField(blank=True, choices=[('HE', 'Heart'), ('IN', 'Intestines'), ('KI', 'Kidneys'), ('LI', 'Liver'), ('LU', 'Lungs'), ('PA', 'Pancreas')], max_length=2, null=True),
        ),
    ]
