# Generated by Django 3.0.3 on 2022-10-30 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_organdonation_organ_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_appointment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='category',
            field=models.CharField(choices=[('PED', 'Pediatrician'), ('CAR', 'Cardiologist'), ('ONC', 'Oncologist'), ('GAS', 'Gastroenterologist'), ('PUL', 'Pulmonologist'), ('END', 'Endocrinologist'), ('OPH', 'Ophthalmologist'), ('DER', 'Dermatologist'), ('NEU', 'Neurologist'), ('RAD', 'Radiologist'), ('SUR', 'Surgeon'), ('PAT', 'Patient')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospitalactor',
            name='category',
            field=models.CharField(blank=True, choices=[('PED', 'Pediatrician'), ('CAR', 'Cardiologist'), ('ONC', 'Oncologist'), ('GAS', 'Gastroenterologist'), ('PUL', 'Pulmonologist'), ('END', 'Endocrinologist'), ('OPH', 'Ophthalmologist'), ('DER', 'Dermatologist'), ('NEU', 'Neurologist'), ('RAD', 'Radiologist'), ('SUR', 'Surgeon'), ('PAT', 'Patient')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalactor',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GL', 'Georgia'), ('HI', 'Hawaii'), ('IL', 'Illinois'), ('KS', 'Kansas'), ('MD', 'Maryland'), ('NY', 'New York'), ('ND', 'North Dakota'), ('TX', 'Texas'), ('VA', 'Virginia'), ('MO', 'Missouri'), ('MI', 'Michigan'), ('NJ', 'New Jersey'), ('WI', '\tWisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='organdonation',
            name='category',
            field=models.CharField(choices=[('PED', 'Pediatrician'), ('CAR', 'Cardiologist'), ('ONC', 'Oncologist'), ('GAS', 'Gastroenterologist'), ('PUL', 'Pulmonologist'), ('END', 'Endocrinologist'), ('OPH', 'Ophthalmologist'), ('DER', 'Dermatologist'), ('NEU', 'Neurologist'), ('RAD', 'Radiologist'), ('SUR', 'Surgeon'), ('PAT', 'Patient')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='organdonation',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GL', 'Georgia'), ('HI', 'Hawaii'), ('IL', 'Illinois'), ('KS', 'Kansas'), ('MD', 'Maryland'), ('NY', 'New York'), ('ND', 'North Dakota'), ('TX', 'Texas'), ('VA', 'Virginia'), ('MO', 'Missouri'), ('MI', 'Michigan'), ('NJ', 'New Jersey'), ('WI', '\tWisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='category',
            field=models.CharField(choices=[('PED', 'Pediatrician'), ('CAR', 'Cardiologist'), ('ONC', 'Oncologist'), ('GAS', 'Gastroenterologist'), ('PUL', 'Pulmonologist'), ('END', 'Endocrinologist'), ('OPH', 'Ophthalmologist'), ('DER', 'Dermatologist'), ('NEU', 'Neurologist'), ('RAD', 'Radiologist'), ('SUR', 'Surgeon'), ('PAT', 'Patient')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
