# Generated by Django 3.0.3 on 2022-10-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221030_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organdonation',
            name='category',
        ),
    ]
