# Generated by Django 3.0.3 on 2022-10-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_organdonation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment_notes',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
