# Generated by Django 3.0.3 on 2022-11-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_treatment_treatment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalactor',
            name='email',
            field=models.EmailField(blank=True, default=5, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
